export const sampleCustomers = [
  {
    Id: 'ALFKI',
    CompanyName: 'Alfreds Futterkiste',
    ContactName: 'Maria Anders',
    ContactTitle: 'Sales Representative',
    City: 'Berlin',
  },
  {
    Id: 'ANATR',
    CompanyName: 'Ana Trujillo Emparedados y helados',
    ContactName: 'Ana Trujillo',
    ContactTitle: 'Owner',
    City: 'México D.F.',
  },
  {
    Id: 'ANTON',
    CompanyName: 'Antonio Moreno Taquería',
    ContactName: 'Antonio Moreno',
    ContactTitle: 'Owner',
    City: 'México D.F.',
  },
  {
    Id: 'AROUT',
    CompanyName: 'Around the Horn',
    ContactName: 'Thomas Hardy',
    ContactTitle: 'Sales Representative',
    City: 'London',
  },
  {
    Id: 'BERGS',
    CompanyName: 'Berglunds snabbköp',
    ContactName: 'Christina Berglund',
    ContactTitle: 'Order Administrator',
    City: 'Luleå',
  },
  {
    Id: 'BLAUS',
    CompanyName: 'Blauer See Delikatessen',
    ContactName: 'Hanna Moos',
    ContactTitle: 'Sales Representative',
    City: 'Mannheim',
  },
  {
    Id: 'BLONP',
    CompanyName: 'Blondesddsl père et fils',
    ContactName: 'Frédérique Citeaux',
    ContactTitle: 'Marketing Manager',
    City: 'Strasbourg',
  },
  {
    Id: 'BOLID',
    CompanyName: 'Bólido Comidas preparadas',
    ContactName: 'Martín Sommer',
    ContactTitle: 'Owner',
    City: 'Madrid',
  },
  {
    Id: 'BONAP',
    CompanyName: 'Bon app',
    ContactName: 'Laurence Lebihan',
    ContactTitle: 'Owner',
    City: 'Marseille',
  },
  {
    Id: 'BOTTM',
    CompanyName: 'Bottom-Dollar Markets',
    ContactName: 'Elizabeth Lincoln',
    ContactTitle: 'Accounting Manager',
    City: 'Tsawassen',
  },
];

export const customers = [
  {
    id: 0,
    fullName: 'Maria Anders',
    gender: 'Female',
    description: 'Sales Representative',
    address: 'Obere Str. 57',
    birthDate: new Date('1985-01-15'),
  },
  {
    id: 1,
    fullName: 'Ana Trujillo',
    gender: 'Female',
    description: 'Owner',
    address: 'Avda. de la Constitución 2222',
    birthDate: new Date('1985-01-15'),
  },
  {
    id: 2,
    fullName: 'Antonio Moreno',
    gender: 'Male',
    description: 'Owner',
    address: 'Mataderos  2312',
    birthDate: new Date('1985-01-15'),
  },
  {
    id: 3,
    fullName: 'Thomas Hardy',
    gender: 'Male',
    description: 'Sales Representative',
    address: '120 Hanover Sq.',
    birthDate: new Date('1985-01-15'),
  },
  {
    id: 4,
    fullName: 'Christina Berglund',
    gender: 'Female',
    description: 'Order Administrator',
    address: 'Berguvsvägen  8',
    birthDate: new Date('1985-01-15'),
  },
];
export default customers;
